### ISSUE TITLE
has_function 

### ISSUE THREAD

**Issue by animalcarpet** [hepabolu/mytap#11]
Hi,

I forked your project a couple of weeks back and have been working on extending some of the tests but keep hitting a brick wall trying to run functions in the mytap-routines.sql file.

e.g.
mysql> SELECT tap.has_function('sakila','inventory_in_stock','');
ERROR 1264 (22003): Out of range value for column 'CHARACTER_MAXIMUM_LENGTH' at row 1

I can run the database test on it's own
e.g.
mysql> SELECT tap._has_routine('sakila','inventory_in_stock','FUNCTION');
+------------------------------------------------------------+
| tap._has_routine('sakila','inventory_in_stock','FUNCTION') |
+------------------------------------------------------------+
|                                                                      1 |
+------------------------------------------------------------+
1 row in set (0.00 sec)

and, after altering _has_routine so it has a function body of RETURN 1 , I can select has_function successfully and produce tap output.

I've no issues with any of the column, table or view tests, they're all fine.

I've been through information_schema.routines, there's nothing dubious in CHARACTER_MAXIMUM_LENGTH, not that we're actually touching that column here.

The raw query comes back correctly as

mysql> SELECT true into @b_result FROM information_schema.routines as db WHERE db.routine_schema = 'sakila' AND db.routine_name = 'inventory_in_stock'  AND db.routine_type = 'FUNCTION';
Query OK, 1 row affected (0.01 sec)

mysql> select @b_result;
+-----------+
| @b_result |
+-----------+
|         1 |
+-----------+
1 row in set (0.00 sec)

This query also comes back fine.

and the row queries as
 
mysql> SELECT * FROM `information_schema`.`routines` WHERE `routine_schema` = 'sakila' AND `routine_name` = 'inventory_in_stock' AND `routine_type` = 'FUNCTION'\G
*************************** 1. row ***************************
           SPECIFIC_NAME: inventory_in_stock
         ROUTINE_CATALOG: def
          ROUTINE_SCHEMA: sakila
            ROUTINE_NAME: inventory_in_stock
            ROUTINE_TYPE: FUNCTION
               DATA_TYPE: tinyint
CHARACTER_MAXIMUM_LENGTH: NULL
  CHARACTER_OCTET_LENGTH: NULL
       NUMERIC_PRECISION: 3
           NUMERIC_SCALE: 0
      DATETIME_PRECISION: NULL
      CHARACTER_SET_NAME: NULL
          COLLATION_NAME: NULL
          DTD_IDENTIFIER: tinyint(1)
            ROUTINE_BODY: SQL
      ROUTINE_DEFINITION: BEGIN
    DECLARE v_rentals INT;
    DECLARE v_out     INT;

    
    

    SELECT COUNT(*) INTO v_rentals
    FROM rental
    WHERE inventory_id = p_inventory_id;

    IF v_rentals = 0 THEN
      RETURN TRUE;
    END IF;

    SELECT COUNT(rental_id) INTO v_out
    FROM inventory LEFT JOIN rental USING(inventory_id)
    WHERE inventory.inventory_id = p_inventory_id
    AND rental.return_date IS NULL;

    IF v_out > 0 THEN
      RETURN FALSE;
    ELSE
      RETURN TRUE;
    END IF;
END
           EXTERNAL_NAME: NULL
       EXTERNAL_LANGUAGE: NULL
         PARAMETER_STYLE: SQL
        IS_DETERMINISTIC: NO
         SQL_DATA_ACCESS: READS SQL DATA
                SQL_PATH: NULL
           SECURITY_TYPE: DEFINER
                 CREATED: 2017-11-04 15:10:48
            LAST_ALTERED: 2017-11-04 15:10:48
                SQL_MODE: STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
         ROUTINE_COMMENT: 
                 DEFINER: paul@localhost
    CHARACTER_SET_CLIENT: utf8
    COLLATION_CONNECTION: utf8_general_ci
      DATABASE_COLLATION: latin1_swedish_ci
1 row in set (0.01 sec)

I've googled the error and found nothing relevant, run the function against 4 different schemas, I've even tried on a fresh install of mysql (5.7.20), same result. Have you seen this error before?

Thanks

**Comment by hepabolu** [comment]
I've seen something similar and if I remember correctly it was related to MySQL 5.7. Could you try it on a MySQL 5.5/5.6 installation? Just to verify my suspicion.

**Comment by animalcarpet** [comment]
Thanks for replying so quickly.

I've carried on looking at this and I think I've narrowed it down to the SQL MODE settings. If I load the function with @@SESSION.sql_mode='' then these.functions start working.

I've yet to test to see exactly which mode is causing the problem but some more searching has turned up http://moinne.com/blog/ronald/mysql/use-the-strict-sql-mode-when-compiling-a-mysql-stored-procedure-to-avoid-unexpected-errors which points to STRICT_ALL_TABLES as a potential culprit. The only thing I can see wrong with the data types is the routine_type which ought to be VARCHAR(9) and that should be erring on the right side. Even with the param set to match those in information_schema.routines I still get the error. Neither can I understand why it would be fine for all the other functions with the same mode in operation and not these ones since the functions are essentially the same with the table name and identifiers changed.  

The defaults get very strict after 5.7.8 (https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-changes) so it's likely the problem will affect people running newer versions.

I'll let you know when I've finally nailed down which mode is the problem. A workaround would be to set the mode explicitly when importing the functions but then you'd lose the benefit of strict mode which is a bit self-defeating when you want to test it's correct in the first place.

**Comment by hepabolu** [comment]
Thanks for looking into this. I currently don’t have much time to investigate this and it seems you’re way ahead of me nailing this problem.

**Comment by animalcarpet** [comment]
Still looking.

I tested it in 5.5 and it's fine in strict mode. However, both STRICT_ALL_TABLES and STRICT_TRANS_TABLES cause the problem in 5.7.

I've been down the path of checking whether there was a problem with the __tcache__ and __tresults__ tables since they are the only ones this might write to, can't see any issue with them. I've checked for collations and character sets. Still coming up a blank. 

The only thing that works is removing strict mode. Confused about how CHARACTER_MAXIMUM_LENGTH comes into this at all and why only in relation to the routines table and not the columns table.

**Comment by hepabolu** [comment]
Just a hunch. I noticed the database collation is latin1 while the table collation is utf8. Could that cause trouble?

**Comment by animalcarpet** [comment]
Unfortunately, I'd tried that one already with no joy (see below). 


*************************** 1. row ***************************
           SPECIFIC_NAME: has_function
...
      CHARACTER_SET_NAME: latin1
          COLLATION_NAME: latin1_swedish_ci
...
              SQL_MODE: STRICT_ALL_TABLES
...
    CHARACTER_SET_CLIENT: latin1
    COLLATION_CONNECTION: latin1_swedish_ci
      DATABASE_COLLATION: latin1_swedish_ci
1 row in set (0.02 sec)

mysql> select tap.has_function('tap','has_function','');
ERROR 1264 (22003): Out of range value for column 'CHARACTER_MAXIMUM_LENGTH' at row 1

**Comment by animalcarpet** [comment]
I hate to admit defeat on this but I'm starting to suspect there's a bug in the implementation of this view in 5.7 

The code for routines is essentially the same as for all the other object types, the only difference is that it's accessing the routines table.
The column referred to isn't referenced anywhere in the code. 
I'm a bit curious as to why the definitions for the routines and columns views differ on this field

mysql> show create table information_schema.routines\G
*************************** 1. row ***************************
       Table: ROUTINES
Create Table: CREATE TEMPORARY TABLE `ROUTINES` (
  `SPECIFIC_NAME` varchar(64) NOT NULL DEFAULT '',
  `ROUTINE_CATALOG` varchar(512) NOT NULL DEFAULT '',
  `ROUTINE_SCHEMA` varchar(64) NOT NULL DEFAULT '',
  `ROUTINE_NAME` varchar(64) NOT NULL DEFAULT '',
  `ROUTINE_TYPE` varchar(9) NOT NULL DEFAULT '',
  `DATA_TYPE` varchar(64) NOT NULL DEFAULT '',
  **`CHARACTER_MAXIMUM_LENGTH` int(21) DEFAULT NULL,
  `CHARACTER_OCTET_LENGTH` int(21) DEFAULT NULL,**
  `NUMERIC_PRECISION` bigint(21) unsigned DEFAULT NULL,
  `NUMERIC_SCALE` int(21) DEFAULT NULL,
  `DATETIME_PRECISION` bigint(21) unsigned DEFAULT NULL,
  `CHARACTER_SET_NAME` varchar(64) DEFAULT NULL,
  `COLLATION_NAME` varchar(64) DEFAULT NULL,
  `DTD_IDENTIFIER` longtext,
  `ROUTINE_BODY` varchar(8) NOT NULL DEFAULT '',
  `ROUTINE_DEFINITION` longtext,
  `EXTERNAL_NAME` varchar(64) DEFAULT NULL,
  `EXTERNAL_LANGUAGE` varchar(64) DEFAULT NULL,
  `PARAMETER_STYLE` varchar(8) NOT NULL DEFAULT '',
  `IS_DETERMINISTIC` varchar(3) NOT NULL DEFAULT '',
  `SQL_DATA_ACCESS` varchar(64) NOT NULL DEFAULT '',
  `SQL_PATH` varchar(64) DEFAULT NULL,
  `SECURITY_TYPE` varchar(7) NOT NULL DEFAULT '',
  `CREATED` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_ALTERED` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `SQL_MODE` varchar(8192) NOT NULL DEFAULT '',
  `ROUTINE_COMMENT` longtext NOT NULL,
  `DEFINER` varchar(93) NOT NULL DEFAULT '',
  `CHARACTER_SET_CLIENT` varchar(32) NOT NULL DEFAULT '',
  `COLLATION_CONNECTION` varchar(32) NOT NULL DEFAULT '',
  `DATABASE_COLLATION` varchar(32) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8
1 row in set (0.00 sec)

mysql> show create table information_schema.columns\G
*************************** 1. row ***************************
       Table: COLUMNS
Create Table: CREATE TEMPORARY TABLE `COLUMNS` (
  `TABLE_CATALOG` varchar(512) NOT NULL DEFAULT '',
  `TABLE_SCHEMA` varchar(64) NOT NULL DEFAULT '',
  `TABLE_NAME` varchar(64) NOT NULL DEFAULT '',
  `COLUMN_NAME` varchar(64) NOT NULL DEFAULT '',
  `ORDINAL_POSITION` bigint(21) unsigned NOT NULL DEFAULT '0',
  `COLUMN_DEFAULT` longtext,
  `IS_NULLABLE` varchar(3) NOT NULL DEFAULT '',
  `DATA_TYPE` varchar(64) NOT NULL DEFAULT '',
  **`CHARACTER_MAXIMUM_LENGTH` bigint(21) unsigned DEFAULT NULL,
  `CHARACTER_OCTET_LENGTH` bigint(21) unsigned DEFAULT NULL,**
  `NUMERIC_PRECISION` bigint(21) unsigned DEFAULT NULL,
  `NUMERIC_SCALE` bigint(21) unsigned DEFAULT NULL,
  `DATETIME_PRECISION` bigint(21) unsigned DEFAULT NULL,
  `CHARACTER_SET_NAME` varchar(32) DEFAULT NULL,
  `COLLATION_NAME` varchar(32) DEFAULT NULL,
  `COLUMN_TYPE` longtext NOT NULL,
  `COLUMN_KEY` varchar(3) NOT NULL DEFAULT '',
  `EXTRA` varchar(30) NOT NULL DEFAULT '',
  `PRIVILEGES` varchar(80) NOT NULL DEFAULT '',
  `COLUMN_COMMENT` varchar(1024) NOT NULL DEFAULT '',
  `GENERATION_EXPRESSION` longtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8
1 row in set (0.00 sec)

**Comment by hepabolu** [comment]
Thanks for the bug report.  I do hope that we’re getting feedback and possibly a solution.

**Comment by animalcarpet** [comment]
Happy to report that, after initially deciding that this was a documentation issue, the problems has now been accepted as a bug, and is seemingly a simple enough fix, Assuming the suggested fix solves the problem I'm experiencing everything will be fine for future versions of mysql but that's not going to help anyone who is stuck with a broken version. 

You can work around the problem by removing strict_mode for the session when importing the routine. The only question is whether it is appropriate to put in a fix which changes sql_mode (which I'm not entirely comfortable with no matter how isolated that change is) or put instructions for affected users within the documentation. Do you have a preference here?

**Comment by hepabolu** [comment]
Does the workaround apply only to specific 5.7 versions? If so I’d rather document it with the workaround than add the fix. 
Or can we apply the workaround using the version comments?  The need for documentation is still necessary but then it’s clear where the workaround should be applied.
Does that help?

**Comment by hepabolu** [comment]
I'll close this issue because it is part of #14 as explained in #13 .
