### ISSUE TITLE
[typo?] documentation states pgTAP behavior for todo, not myTAP

### ISSUE THREAD

**Issue by hauntingEcho** [hepabolu/mytap#12]
most likely just a typo (s/pg/my), but the documentation for `todo( how_many, why )`  states `pgTAP will run the tests normally, but print out special flags indicating they are “todo” tests.` but does not state myTAP behavior

https://hepabolu.github.io/mytap/documentation/

**Comment by hepabolu** [comment]
good catch. Thank you.
