### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by animalcarpet** [hepabolu/mytap#13]
Helma,
I've been working for some time on my fork of this repository and reached a point where I've done all the things I'd like to achieve with the code. At this point I'd be looking to do a pull request into the main repository in the hope that you'd take the changes. However, I tend to work in concentrated bursts and I tend to make rather sweeping changes to which can affect large sections of the code so the my fork eyour repository have now converged considerably. I'll summarise the main differences.

The categories of database objects that can be tested now extends to

mytap-global.sql (variables)
mytap-schemata.sql
mytap-engine.sql
mytap-collation.sql
mytap-charset.sql
mytap-user.sql
mytap-event.sql
mytap-table.sql
mytap-view.sql
mytap-column.sql
mytap-trigger.sql
mytap-routines.soriesql
mytap-constraint.sql
mytap-index.sql
mytap-partition.sql

Within each class of object, I've added methods to test most, if not always all, the properties of the object that can be found in the information_schema. I've also added tests, which exist in pgTAP, to ensure that only the correct objects exist e.g. columns_are(), tables_are(), routines_are etc.

Function parameters have been changed from TEXT to match the specification of the schema object being tested, so schema, table and column  names are all VARCHAR(64) etc. Parameter names more closely match the objects tested and are applied consistently.

Default descriptions are moved before any diagnostic tests. This makes it possible to see which test the diagnostic message applies to rather than overwriting the description as currently happens. Diagnostic tests are applied to check the existence of the parent object of the one being tested. I think this is currently broken in every testing function.

I've rewritten the tests to provide comprehensive coverage for all the new object tests. Although check_test allows 3 aspects of the function to be tested simultaneously I've separated the testing of pass/fail from the test on the description and diagnostic messages because I'm of the school that believes tests each test should test should apply to one, and only one, aspect under test.
 
I've added a script autotap.sql which, given a schema name, will generate appropriate tests to check all objects in the shema. The assumption is that the current state is actually correct. This should allow people to retrofit TAP tests to existing projects. For example, if you apply the script to the sakila test database it will generate 1168 tests on the schema, tables, view, columns, constraints, indexes etc.

The changes are rather extensive, so I think it might be useful if you were able to look over my fork to see if there's any aspect you don't agree which I could change and decide if it's appropriate to pull the changes into the main repo.

Paul Campbell

**Comment by hepabolu** [comment]
Hi @animalcarpet. That sounds promising. I’m more than happy to consider including your pull request. However, for clarity it might be best to create many small pull requests that are more easily to follow rather than large pull requests that touch a lot of code at once. If nothing else, it’ll help me figure out what happened and why it’s an improvement.
Is that doable?

**Comment by animalcarpet** [comment]
Helma,
This is why I thought it might be a good to have a chat about it first ... Short of cherry picking individual commits I don't know how to do that. I didn't branch for separate features (big mistake) and the nature of some of the changes leaves very little unchanged fro tom the original (e.g. use of MySQL standard coding conventions). Also, things like the tests we're written in one burst last week rather than as the other changes were made so they are dependent on the totality of the other changes.

My suggestion would be to diff the existing files against the fork to see the changes with
https://github.com/hepabolu/mytap/compare/master...animalcarpet:master#files_bucket

That would let you see whether you think it even worth attempting to go further with the exercise.

Paul

**Comment by hepabolu** [comment]
It doesn’t look like an easy comparison. I’ll need some time to go over this. I’ll get back to you once I’ve figured out what happened.
BTW did you include a fix for the MySQL bug re stored procedures you found earlier?

**Comment by animalcarpet** [comment]
Yes, the fix for that is to reset sql_mode which is at the top of mytap-routines.sql and then set it back again at the foot of the file.

The comparison is, as you say, not easy. I think it's more a question of seeing the point behind a change. Some bits should be easy to accept, e.g. swapping set description and diagnostics, that's just broken at the moment. I'd say the parameter changes are also probably better coding practice because it helps to identify errors in use. Others are stylistic or a matter of personal preference e.g. using 1/0 for function returns rather than true/false, dropping unnecessary aliases, even formatting code and SQL. I'd say that some of the extensions will probably not find favour in every quarter - autotap test generation, especially, will go against the grain for testing purists, others might not like the idea of testing users in the same package since they are not part of information_schema.

**Comment by hepabolu** [comment]
Hello @animalcarpet. I'm more than happy to include your pull request. I've gone over your commits and can more or less follow what you've done. There is only one concern I have and I haven't yet figured it out by myself: are there any changes in the naming of the functions and/or parameter lists/order?
We use this library in our company very extensively so any changes in the name or parameter list of the functions that are already there, will throw our own code out of whack.
If so, I'd rather have some of these functions restored (i.e. call the new functions) for backward compatibility.

**Comment by hepabolu** [comment]
@animalcarpet Can you do the hard work and incorporate my changes in v0.07 in your version? Then I'd be more than happy to include your code in the repo.

**Comment by animalcarpet** [comment]
Helma, That's great. There has been some chopping and changing but, off the top of my head, I can only think of one place where it will break backward compatibility and that's with triggers. The has_trigger() function was part of mytap-tables.sql. I expanded the trigger coverage and moved the function into the new file. In the move I did change the parameters to add the table_name. The reason I did this is because of the very strong association between a trigger and the table the event takes place on and in spite the fact that trigger names are unique within a schema and not to the table level. For consistency with the other functions I wanted to test for the existence of the parent object, i.e. the table, and this also made it share a common parameter set with all other objects where the parent is a table, e.g. columns, indexes, keys etc. The change is really down to how I conceptualise schema objects within a hierarchy.

I can't think of any others at the moment so I think the way forward would be for me to extract the function names and parameter for both versions and do a thorough check and then we can resolve the issues from there.

**Comment by animalcarpet** [comment]
OK, I think I have the two merged now. If you look at the commit history on my fork you should see all your changes incorporated. As far as I can see there are now no changes which would break backward compatibility (has_type() had a breaking change but I've changed it back). If I missed anything let me know and I'll correct it.  I have, however, made a change to runtests.sh to allow for users who have ~/.my.cnf set up to avoid username/password on the cmdline. 

This is the comparison of function params I conducted  - those with dbname as the first param are the originals, any that aren't duplicates are new functions. Once you are happy that I've got the two versions synched I'll do the pull request.

```
paul@zoltan:~/git$ find oldtap mytap -name "mytap-*.sql" | xargs grep 'CREATE FUNCTION' | awk -F'CREATE FUNCTION ' {'print $2'} | grep -v "^_" | sort col_character_set_is(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), cset VARCHAR(32), description TEXT)
col_charset_is(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), cset VARCHAR(32), description TEXT)
col_collation_is(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), ccoll VARCHAR(32), description TEXT)
col_column_type_is(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), ctype LONGTEXT, description TEXT)
col_data_type_is(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), dtype LONGTEXT, description TEXT)
col_default_is ( dbname TEXT, tname TEXT, cname TEXT, cdefault TEXT, description TEXT )
col_default_is(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), cdefault LONGTEXT, description TEXT)
col_extra_is ( dbname TEXT, tname TEXT, cname TEXT, cextra TEXT, description TEXT )
col_extra_is(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), cextra VARCHAR(30), description TEXT)
col_has_default ( dbname TEXT, tname TEXT, cname TEXT, description TEXT )
col_has_default(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), description TEXT)
col_has_index_key ( dbname TEXT, tname TEXT, cname TEXT, description TEXT )
col_has_index_key(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), description TEXT)
col_has_named_index ( dbname TEXT, tname TEXT, cname TEXT, kname TEXT, description TEXT )
col_has_named_index(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), kname VARCHAR(64), description TEXT)
col_has_non_unique_index ( dbname TEXT, tname TEXT, cname TEXT, description TEXT )
col_has_non_unique_index(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), description TEXT)
col_hasnt_default ( dbname TEXT, tname TEXT, cname TEXT, description TEXT )
col_hasnt_default(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), description TEXT)
col_hasnt_index_key ( dbname TEXT, tname TEXT, cname TEXT, description TEXT )
col_hasnt_index_key(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), description TEXT)
col_hasnt_named_index ( dbname TEXT, tname TEXT, cname TEXT, kname TEXT, description TEXT )
col_hasnt_named_index(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), kname TEXT, description TEXT)
col_hasnt_non_unique_index ( dbname TEXT, tname TEXT, cname TEXT, description TEXT )
col_hasnt_non_unique_index(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), description TEXT)
col_hasnt_pos_in_named_index ( dbname TEXT, tname TEXT, cname TEXT, kname TEXT, position INT, description TEXT )
col_hasnt_pos_in_named_index(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), kname VARCHAR(64), pos INT, description TEXT)
col_hasnt_primary_key ( dbname TEXT, tname TEXT, cname TEXT, description TEXT )
col_hasnt_primary_key(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), description TEXT)
col_hasnt_unique_index ( dbname TEXT, tname TEXT, cname TEXT, description TEXT )
col_hasnt_unique_index (sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), description TEXT)
col_has_pos_in_named_index ( dbname TEXT, tname TEXT, cname TEXT, kname TEXT, position INT, description TEXT )
col_has_pos_in_named_index(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), kname VARCHAR(64), pos INT, description TEXT)
col_has_primary_key ( dbname TEXT, tname TEXT, cname TEXT, description TEXT )
col_has_primary_key(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), description TEXT)
col_has_type ( dbname TEXT, tname TEXT, cname TEXT, ctype TEXT, description TEXT )
col_has_type(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), ctype VARCHAR(64), description TEXT)
col_has_unique_index ( dbname TEXT, tname TEXT, cname TEXT, description TEXT )
col_has_unique_index (sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), description TEXT)
col_is_null ( dbname TEXT, tname TEXT, cname TEXT, description TEXT )
col_is_null(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), description TEXT)
col_is_pk(sname VARCHAR(64), tname VARCHAR(64), want TEXT, description TEXT)
col_is_unique(sname VARCHAR(64), tname VARCHAR(64), want TEXT, description TEXT)
col_not_null ( dbname TEXT, tname TEXT, cname TEXT, description TEXT )
col_not_null(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), description TEXT)
columns_are(sname VARCHAR(64), tname VARCHAR(64), want TEXT, description TEXT)
constraints_are(sname VARCHAR(64), tname VARCHAR(64),  want TEXT, description TEXT)
constraint_type_is(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), ctype VARCHAR(64), description TEXT)
engine_is_default(ename VARCHAR(64), description TEXT)
event_interval_field_is(sname VARCHAR(64), ename VARCHAR(64), ifield VARCHAR(18), description TEXT)
event_interval_value_is(sname VARCHAR(64), ename VARCHAR(64), ivalue VARCHAR(256), description TEXT)
events_are(sname VARCHAR(64), want TEXT, description TEXT)
event_status_is(sname VARCHAR(64), ename VARCHAR(64), stat VARCHAR(18), description TEXT)
event_type_is(sname VARCHAR(64), ename VARCHAR(64), etype VARCHAR(9), description TEXT)
fk_ok(csch VARCHAR(64), ctab VARCHAR(64), ccol TEXT,
fk_on_delete(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), rule VARCHAR(64), description TEXT)
fk_on_update(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), rule VARCHAR(64), description TEXT)
function_data_type_is(sname VARCHAR(64), rname VARCHAR(64), dtype VARCHAR(64), description TEXT)
function_is_deterministic(sname VARCHAR(64), rname VARCHAR(64), val VARCHAR(3), description TEXT)
function_security_type_is(sname VARCHAR(64), rname VARCHAR(64), stype VARCHAR(7), description TEXT)
function_sql_data_access_is(sname VARCHAR(64), rname VARCHAR(64), sda VARCHAR(64), description TEXT)
global_is(var VARCHAR(64), want VARCHAR(1024), description TEXT)
has_character_set(cname VARCHAR(32), description TEXT)
has_charset(cname VARCHAR(32), description TEXT)
has_collation(cname VARCHAR(32), description TEXT)
has_column ( dbname TEXT, tname TEXT, cname TEXT, description TEXT )
has_column(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), description TEXT)
has_constraint(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), description TEXT)
has_engine(ename VARCHAR(64), description TEXT)
has_event(sname VARCHAR(64), ename VARCHAR(64), description TEXT)
has_fk(sname VARCHAR(64), tname VARCHAR(64), description TEXT)
has_function ( dbname TEXT, rname TEXT, description TEXT )
has_function(sname VARCHAR(64), rname VARCHAR(64), description TEXT)
has_index(sname VARCHAR(64), tname VARCHAR(64), iname VARCHAR(64), description TEXT)
hasnt_character_set(cname VARCHAR(32), description TEXT)
hasnt_charset(cname VARCHAR(32), description TEXT)
hasnt_collation(cname VARCHAR(32), description TEXT)
hasnt_column ( dbname TEXT, tname TEXT, cname TEXT, description TEXT )
hasnt_column(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), description TEXT)
hasnt_constraint(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), description TEXT)
hasnt_event(sname VARCHAR(64), ename VARCHAR(64), description TEXT)
hasnt_fk(sname VARCHAR(64), tname VARCHAR(64), description TEXT)
hasnt_function ( dbname TEXT, rname TEXT, description TEXT )
hasnt_function(sname VARCHAR(64), rname VARCHAR(64), description TEXT)
hasnt_index(sname VARCHAR(64), tname VARCHAR(64), iname VARCHAR(64), description TEXT)
hasnt_partition(sname VARCHAR(64), tname VARCHAR(64), part VARCHAR(64), description TEXT)
hasnt_pk(sname VARCHAR(64), tname VARCHAR(64), description TEXT)
hasnt_procedure ( dbname TEXT, rname TEXT, description TEXT )
hasnt_procedure(sname VARCHAR(64), rname VARCHAR(64), description TEXT)
hasnt_routine(sname VARCHAR(64), rname VARCHAR(64), rtype VARCHAR(9), description TEXT)
hasnt_schema(sname VARCHAR(64), description TEXT)
hasnt_subpartition(sname VARCHAR(64), tname VARCHAR(64), subp VARCHAR(64), description TEXT)
hasnt_table (dbname TEXT, tname TEXT, description TEXT)
hasnt_table(sname VARCHAR(64), tname VARCHAR(64), description TEXT)
hasnt_trigger( dbname TEXT, tname TEXT, triggername TEXT, description TEXT )
hasnt_trigger(sname VARCHAR(64), tname VARCHAR(64), trgr VARCHAR(64), description TEXT)
hasnt_user(hname CHAR(60), uname CHAR(32), description TEXT)
hasnt_view(dbname TEXT, vname TEXT, description TEXT) RETURNS TEXT
hasnt_view(sname VARCHAR(64), vname VARCHAR(64), description TEXT)
has_partitioning(description TEXT)
has_partition(sname VARCHAR(64), tname VARCHAR(64), part VARCHAR(64), description TEXT)
has_pk(sname VARCHAR(64), tname VARCHAR(64), description TEXT)
has_procedure ( dbname TEXT, rname TEXT, description TEXT )
has_procedure(sname VARCHAR(64), rname VARCHAR(64), description TEXT)
has_routine(sname VARCHAR(64), rname VARCHAR(64), rtype VARCHAR(9), description TEXT)
has_schema(sname VARCHAR(64), description TEXT)
has_security_definer(dbname TEXT, vname TEXT, description TEXT) RETURNS TEXT
has_security_definer(sname VARCHAR(64), vname VARCHAR(64), description TEXT)
has_security_invoker(dbname TEXT, vname TEXT, description TEXT) RETURNS TEXT
has_security_invoker(sname VARCHAR(64), vname VARCHAR(64), description TEXT)
has_subpartition(sname VARCHAR(64), tname VARCHAR(64), subp VARCHAR(64), description TEXT)
has_table (dbname TEXT, tname TEXT, description TEXT)
has_table(sname VARCHAR(64), tname VARCHAR(64), description TEXT)
has_trigger( dbname TEXT, tname TEXT, triggername TEXT, description TEXT )
has_trigger(sname VARCHAR(64), tname VARCHAR(64), trgr VARCHAR(64), description TEXT)
has_unique(sname VARCHAR(64), tname VARCHAR(64), description TEXT)
has_user(hname CHAR(60), uname CHAR(32), description TEXT)
has_view(dbname TEXT, vname TEXT, description TEXT) RETURNS TEXT
has_view(sname VARCHAR(64), vname VARCHAR(64), description TEXT)
indexes_are(sname VARCHAR(64), tname VARCHAR(64),  want TEXT, description TEXT)
index_is(sname VARCHAR(64), tname VARCHAR(64), iname VARCHAR(64), want TEXT, description TEXT)
index_is_type(sname VARCHAR(64), tname VARCHAR(64), iname VARCHAR(64), itype VARCHAR(64), description TEXT)
is_indexed(sname VARCHAR(64), tname VARCHAR(64), want TEXT, description TEXT)
partition_count_is(sname VARCHAR(64), tname VARCHAR(64), cnt SMALLINT, description TEXT)
partition_expression_is(sname VARCHAR(64), tname VARCHAR(64), part VARCHAR(64), expr LONGTEXT, description TEXT)
partition_method_is(sname VARCHAR(64), tname VARCHAR(64), part VARCHAR(64), pmeth VARCHAR(18), description TEXT)
partitions_are(sname VARCHAR(64), tname VARCHAR(64), want TEXT, description TEXT)
procedure_is_deterministic(sname VARCHAR(64), rname VARCHAR(64), val VARCHAR(3), description TEXT)
procedure_security_type_is(sname VARCHAR(64), rname VARCHAR(64), stype VARCHAR(7), description TEXT)
procedure_sql_data_access_is(sname VARCHAR(64), rname VARCHAR(64), sda VARCHAR(64), description TEXT)
routine_has_sql_mode(sname VARCHAR(64), rname VARCHAR(64), rtype VARCHAR(64), smode VARCHAR(8192), description TEXT)
routine_is_deterministic(sname VARCHAR(64), rname VARCHAR(64), rtype VARCHAR(9), val VARCHAR(3), description TEXT)
routines_are(sname VARCHAR(64), rtype VARCHAR(9), want TEXT, description TEXT)
routine_security_type_is(sname VARCHAR(64), rname VARCHAR(64), rtype VARCHAR(9), stype VARCHAR(7), description TEXT)
routine_sha1_is(sname VARCHAR(64), rname VARCHAR(64), rtype VARCHAR(9), sha1 VARCHAR(40), description TEXT)
routine_sql_data_access_is(sname VARCHAR(64), rname VARCHAR(64), rtype VARCHAR(9), sda VARCHAR(64), description TEXT)
scheduler_is(want VARCHAR(3), description TEXT)
schema_character_set_is(sname VARCHAR(64), cname VARCHAR(32), description TEXT)
schema_charset_is(sname VARCHAR(64), cname VARCHAR(32), description TEXT)
schema_collation_is(sname VARCHAR(64), cname VARCHAR(32), description TEXT)
schemas_are(want TEXT, description TEXT)
subpartition_expression_is(sname VARCHAR(64), tname VARCHAR(64), subp VARCHAR(64), expr LONGTEXT, description TEXT)
subpartition_method_is(sname VARCHAR(64), tname VARCHAR(64), subp VARCHAR(64), smeth VARCHAR(18), description TEXT)
table_character_set_is(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(32), description TEXT)
table_collation_is(sname VARCHAR(64), tname VARCHAR(64), cname VARCHAR(64), description TEXT)
table_engine_is(sname VARCHAR(64), tname VARCHAR(64), ename VARCHAR(32), description TEXT)
tables_are(sname VARCHAR(64), want TEXT, description TEXT)
table_sha1_is(sname VARCHAR(64), tname VARCHAR(64), sha1 VARCHAR(40), description TEXT)
trigger_event_is(sname VARCHAR(64), tname VARCHAR(64), trgr VARCHAR(64), evnt VARCHAR(6), description TEXT)
trigger_is(sname VARCHAR(64), tname VARCHAR(64), trgr VARCHAR(64), act_state LONGTEXT, description TEXT)
trigger_order_is(sname VARCHAR(64), tname VARCHAR(64), trgr VARCHAR(64), seq BIGINT, description TEXT)
triggers_are(sname VARCHAR(64), tname VARCHAR(64), want TEXT, description TEXT)
trigger_timing_is(sname VARCHAR(64), tname VARCHAR(64), trgr VARCHAR(64), timing VARCHAR(6), description TEXT)
user_has_lifetime(hname CHAR(60), uname CHAR(32), description TEXT)
user_hasnt_lifetime(hname CHAR(60), uname CHAR(32), description TEXT)
user_not_ok(hname CHAR(60), uname CHAR(32), description TEXT)
user_ok(hname CHAR(60), uname CHAR(32), description TEXT)
view_check_option_is(sname VARCHAR(64), vname VARCHAR(64), copt VARCHAR(8), description TEXT)
view_definer_is(sname VARCHAR(64), vname VARCHAR(64), dfnr VARCHAR(93), description TEXT)
view_is_updatable(sname VARCHAR(64), vname VARCHAR(64), updl VARCHAR(3), description TEXT)
views_are(sname VARCHAR(64), want TEXT, description TEXT)
view_security_type_is(sname VARCHAR(64), vname VARCHAR(64), stype VARCHAR(7), description TEXT)

```

**Comment by hepabolu** [comment]
I'm happy with the comparison. Looks good.

**Comment by hepabolu** [comment]
I've pull the merged code and ran the tests locally. I'm running into a few issues which might be related to the MySQL version. I'm currently testing against 5.6.38, but I also need the tests to work on a 5.5.x server.
What version did you use to test on?

**Comment by hepabolu** [comment]
I'll close this issue and create new ones for the errors I find, so we can fix them more transparently

**Comment by animalcarpet** [comment]
5.7.something. Which tests are failing, it might be down to feature incompatibility it'll probably be obvious if you post the full output. I'll get those versions running in a container and test them later myself.
