### ISSUE TITLE
test results in multiple rows

### ISSUE THREAD

**Issue by hepabolu** [hepabolu/mytap#18]
MySQL 5.6.38

```
ERROR 1172 (42000) at line 38 in file: 
'tests/test-mytap-view.sql': Result consisted of more than one row
```

**Comment by animalcarpet** [comment]
You can get this after a syntax error when the test numbers get reused. Try 
# mysql -e 'truncate tap.__tresults__'

And run the tests again to see if it clears it.

**Comment by hepabolu** [comment]
true, that solved the problem. I'll close this one.
