### ISSUE TITLE
Check for timezone information

### ISSUE THREAD

**Issue by hepabolu** [hepabolu/mytap#21]
Check if the mysql.time_zone* tables are filled. And/or check if the server correctly handles timezones.

**Comment by animalcarpet** [comment]
The mytap-global.sql that I have just pushed allows querying of @@global.time_zone (or any other global variable) e.g.

```
mysql> select * from performance_schema.global_variables where variable_name like '%time_zone%';
+------------------+----------------+
| VARIABLE_NAME    | VARIABLE_VALUE |
+------------------+----------------+
| system_time_zone | BST            |
| time_zone        | SYSTEM         |
+------------------+----------------+
2 rows in set (0.00 sec)

```

Test with

```
SELECT tap.global_is('time_zone','SYSTEM','');
SELECT tap.global_is('system_time_zone','BST','');

```
Can't really add tests for this because vars will be set differently on individual systems.

**Comment by animalcarpet** [comment]
Helma,
I suspect you are referencing this manual page https://dev.mysql.com/doc/refman/5.7/en/time-zone-upgrades.html

While the test for filled tables is simple, testing that tables have up-to-date data would require tracking changes over time. Do you have any suggestion as to how this could be accomplished given that it's going to be a moving target? I note that the example given on this page goes back to 2007, do you know any more recent examples?

**Comment by hepabolu** [comment]
As far as I can tell there is no sure way to figure out how current the timezone records are i.e. if they contain the most recent version.
However, as I have been bitten a few times by the fact that the timezone records were not available a simple test to check if they are available would help. Also because it usually takes some googling to figure out where they are stored. 
So yes, for now we can settle on 'has_timezones' or something similar.

**Comment by animalcarpet** [comment]
Now pull request #26

**Comment by hepabolu** [comment]
I've reviewed the pull request and it looks ok for me, so go ahead and merge.

**Comment by animalcarpet** [comment]
Merged
