### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by animalcarpet** [hepabolu/mytap#24]
Installer required to match capabilities of runtests.sh (host, port). Provide incremental addition of version files. Consider removal of functions e.g. table_sha1() doesn't work in 8.0 (probably a mysql bug), could revove this functionality from the affected version with a drop function ... in a version file.

**Comment by hepabolu** [comment]
I think it's a good idea to make the test run part of the installer. That way, when installing MyTAP the user will know immediately if something will cause trouble.  For all we know there might be more point upgrade issues between the versions that we're currently unaware of. By running the tests right after installation, we might get the feedback we need to fix it.

I propose to rename the 'runtests.sh' to something like 'installAndTest.sh' and update the documentation accordingly.

**Comment by animalcarpet** [comment]
I've just gone and created an install script ...

I do take your point, if anything I was angling for that outcome and then thought that some would get frustrated by having to wait for the tests to complete so plumped on a separate script. There's a branch on my fork called feature/installer with the changes.

**Comment by hepabolu** [comment]
Well, you typically only install the library when there is a new release, so then you'd want to be sure that all tests succeed in your situation. And it doesn't take a long time for the tests to run.

**Comment by animalcarpet** [comment]
Sorry, belay my last. It doesn't make any sense to filter the install because it is always dependent on the base functions - I'll leave that for the tests.

**Comment by animalcarpet** [comment]
Yes, that's effectively what I've now done, I just think it makes more sense to call it an installer rather than a test-runner. My branch removes runtests.sh. install.sh does the installation and runs the full test suite by default. It also allows tests to be filtered, or skipped (--no-tests).  The --no-install option also allows it to act purely as a test-runner.

**Comment by animalcarpet** [comment]
I can confirm the timezone tests are in master after the merge. I'm closing this issue.
