### ISSUE TITLE
Allow the usage of unix domain socket

### ISSUE THREAD

**Issue by CMCDragonkai** [hepabolu/mytap#29]
It should be able to be set via the options in the install script.

**Comment by animalcarpet** [comment]
That's a reasonable suggestion. The installer is being changed at the moment, I'll add that functionality.

**Comment by animalcarpet** [comment]
This is now included in PR #31

**Comment by hepabolu** [comment]
Reviewed and looks fine to me

**Comment by animalcarpet** [comment]
Merged in
