### ISSUE TITLE
MyTAP test functions should be declared deterministic, where possible

### ISSUE THREAD

**Issue by Ovid** [hepabolu/mytap#3]
When we tried to use MyTAP at work, it seemed to be fine on some dev servers, but for sandboxes, it was failing with the following error:

```
Deploying changes to tap
  + mytap_schema @v0.03 .. ERROR 1418 (HY000) at line 28 in file: '/tmp/o6m_IzqHJP': This function has none of DETERMINISTIC, NO SQL, or READS SQL DATA in its declaration and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)
```

In MySQL, if you have binary logging enabled, functions which are not deterministic might cause issues in data corruption in replication or data restoration. [Here is the relevant section from the MySQL docs](http://dev.mysql.com/doc/refman/5.0/en/stored-programs-logging.html):

> When you create a stored function, you must declare either that it is deterministic or that it does not modify data. Otherwise, it may be unsafe for data recovery or replication.
> 
> By default, for a CREATE FUNCTION statement to be accepted, at least one of DETERMINISTIC, NO SQL, or READS SQL DATA must be specified explicitly. Otherwise an error occurs:
> 
> ERROR 1418 (HY000): This function has none of DETERMINISTIC, NO SQL,
> or READS SQL DATA in its declaration and binary logging is enabled
> (you _might_ want to use the less safe log_bin_trust_function_creators
> variable)
> 
> This function is deterministic (and does not modify data), so it is safe:

``` sql
CREATE FUNCTION f1(i INT)
RETURNS INT
DETERMINISTIC
READS SQL DATA
BEGIN
  RETURN i;
END;
```

> This function uses UUID(), which is not deterministic, so the function also is not deterministic and is not safe:

``` sql
CREATE FUNCTION f2()
RETURNS CHAR(36) CHARACTER SET utf8
BEGIN
  RETURN UUID();
END;
```

**Comment by colmsjo** [comment]
Check out this pull request: https://github.com/theory/mytap/pull/6

**Comment by hepabolu** [comment]
Given the age of this issue and the fact that the mentioned pull request has now been merged, I'll close this issue.
