### ISSUE TITLE
Test user/role privileges

### ISSUE THREAD

**Issue by animalcarpet** [hepabolu/mytap#32]
I'm going to add some user privilege tests. Some will likely be focused around whether a particular privilege has been granted to a certain user and the level at which the privilege is granted e.g. user/role, schema, table.

Any other suggestions would be appreciated.

**Comment by hepabolu** [comment]
First off I think that a test like 'user_has_grants(schema, user, host, grants)' where grants is a comma separated list as string would be a good first version. AKA does this user have the full set of privileges set, and no more.

That might be specialised on table and column level.

Another rabbit hole we/you could get into is 'user_has_grant_on(schema, table, column, user, host, grant)'. AKA given all privileges on the various levels, does the user have the given grant on the schema/table/column given.

Does that make sense?

**Comment by animalcarpet** [comment]
The second one I've already written in four flavours, user, schema, table, column, each level taking account of those that precede it in the hierarchy. 

The first suggestion which says these grants and no more is a good idea, I'll add it in.

**Comment by animalcarpet** [comment]
Helma,

I've pushed a branch feature/privileges to my repo.

I've  added routines as per our discussion. Could you have a look over it and see if it makes sense to you. It still needs documentation but I'm loath to write any if I've got the approach wrong.

**Comment by hepabolu** [comment]
It looks good, I like the way there are several ways to check for privileges.

What I would like to do myself is check if a user has schema privileges and no global privileges. I could do that by testing with an empty string for the global privileges. Could you add tests with empty privileges strings?

**Comment by animalcarpet** [comment]
Hmmmmm. I guess you could do

tap.global_privileges_are(user,'',desc) will give a "not ok" if the user has any global privilege 

mysql> select tap.global_privileges_are('foo@%','','')\G
*************************** 1. row ***************************
tap.global_privileges_are('foo@%','',''): not ok 9 - Account foo@% should have the correct global privileges
# Failed test 9: "Account foo@% should have the correct global privileges"# 
# 
#     Extra Global Privileges:
#        `SUPER`
1 row in set (0.07 sec)

It's tricky to get this right and it's why I asked you to look over it. I imagine that I could ask 10 people for their opinion an get as many answers. In a practical sense it doesn't matter whether an account has a complementary higher level priv when you are testing at the schema or lower level - they can still do whatever to the object concerned irrespective of where they got the privilege. Plus, there's a whole other area I'm ignoring to do with roles and proxies. Perhaps I should take the narrower route and have the tests say it's defined here and nowhere else. Alternatively, I could go the simpler global privs should be x, schema privs should be y, table privs should be x, etc. 

pgtap appears to be using some bult-in functions (https://www.postgresql.org/docs/8.0/static/functions-info.html) for it's privilege queries, these take account of higher levels.

I'll have a think and take another crack at it.

**Comment by hepabolu** [comment]
It’s a security related test: this user should have access to only this schema and nothing else. 
Does that help?

**Comment by animalcarpet** [comment]
Yes.

OK, I've done two new routines single_schema_privileges() and single_table_privileges() which will answer that. I've also changed the other functions so that they can operate in two different modes - rollup, ie accumulated privileges (as it was), and discrete i.e. only concerned with the privileges defined at the level being tested (default). Mode can be switched by setting a user defined variable (SET @rollup=1)

I'll push again when I've written some tests.

**Comment by animalcarpet** [comment]
Tests now passing for these changes. I've written some documentation and merged the outstanding branches and make a single PR for the privileges and the refactoring.

**Comment by hepabolu** [comment]
To me it all looks good. I get a lot of ideas to test if privileges are handed out correctly, but that might be a personal use case and not for everyone. As soon as I find the time, I'm going to look into it. To see if I can create my tests based on the current MyTAP code.

**Comment by animalcarpet** [comment]
I'll merge it in an close the issues.
