### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by animalcarpet** [hepabolu/mytap#36]
When writing the mytap_privileges code I wrote some general methods for dealing with the whateverobjecttype_are style tests. This was to deal with an earlier failure to apply the DRY principle which was only going to get worse with half a dozen new functions requiring temp tables to be populated and their contents compared. 
 
The new code is working successfully in privileges so it seems an excellent opportunity to apply these new methods to the existing object types. This will affect pretty much every mytap-objectname.sql file and result in the removal of hundreds of lines of almost identical code.

I'm proposing a new branch to deal with all of these changes in one go, it'll look like a massive change but there should be no external changes and, of course, the tests will be unchanged.

**Comment by animalcarpet** [comment]
Now done on branch feature/refactor_are_methods.. 900 lines of code changes but the easiest thing in the world to do when all the testing is automated. I branched off feature/privileges for these changes  so a pull request will have to wait till that one is merged.

**Comment by hepabolu** [comment]
I understand what you've done and it looks very good. There is just one issue I can't solve by just looking at the code: what if two sets of tests are running simultaneously and are using the <objecttype>_are at the same time?

We have several mytap test suites that would greatly benefit from these <objecttype>_are tests but they are typically run in parallel.

**Comment by animalcarpet** [comment]
It should be OK, temp tables are specific to the session as well as the user, a different connection even with the same user account shouldn't see them.

> 13.1.18.3 CREATE TEMPORARY TABLE Syntax
> You can use the TEMPORARY keyword when creating a table. A TEMPORARY table is visible only within the current session, and is dropped automatically when the session is closed. This means that two different sessions can use the same temporary table name without conflicting with each other or with an existing non-TEMPORARY table of the same name. (The existing table is hidden until the temporary table is dropped.)

**Comment by hepabolu** [comment]
Great

**Comment by hepabolu** [comment]
I guess this one can be closed now, or is there any reason to keep it open?

**Comment by animalcarpet** [comment]
Thanks for looking over the PR, I'll merge and close.
