### ISSUE TITLE
Problems installing mytap

### ISSUE THREAD

**Issue by sq6jnx** [hepabolu/mytap#44]
I'm trying to install current master (14513c60) on  5.7.27-0ubuntu0.18.04.1. The test suite takes couple of seconds, but fails on:

```
# ...
ok 192 - col_charset_is() description supplied should have the proper description
ok 193 - col_charset_is() column not found diagnostic should fail
ok 194 - col_charset_is() column not found diagnostic should have the proper diagnostics
ERROR 1436 (HY000) at line 1333 in file: 'tests/test-mytap-column.my': Thread stack overrun:  68896 bytes used of a 196608 byte stack, and 128000 bytes needed.  Use 'mysqld --thread_stack=#' to specify a bigger stack.
============= constraints ============
1..127
ERROR 1172 (42000) at line 58 in file: 'tests/test-mytap-constraint.my': Result consisted of more than one row
============= engines ============
1..14
ERROR 1172 (42000) at line 17 in file: 'tests/test-mytap-engine.my': Result consisted of more than one row
============= events ============
1..64
ERROR 1172 (42000) at line 28 in file: 'tests/test-mytap-event.my': Result consisted of more than one row
============= indexes ============
1..57
ERROR 1172 (42000) at line 30 in file: 'tests/test-mytap-index.my': Result consisted of more than one row
============= partitions ============
1..92
ERROR 1172 (42000) at line 64 in file: 'tests/test-mytap-partition.my': Result consisted of more than one row
============= privileges ============
1..208
ERROR 1045 (28000) at line 64 in file: 'tests/test-mytap-privilege.my': Access denied for user 'sq6jnx'@'%' (using password: YES)
============= role ============
1..33
ok 1 - SKIP: Requires MySQL version >= 8.0.11
ok 2 - SKIP: Requires MySQL version >= 8.0.11
ok 3 - SKIP: Requires MySQL version >= 8.0.11
# ...
```

I've tried to `$ sudo mysqld --thread_stack=512000`, but behaviour is the same.

What I've forgot?

**Comment by animalcarpet** [comment]
@sq6jnx 

That's a new one on me.

Interestingly, I'm running the same version as you and the tests complete without issue. 
```
mysql> show variables like 'thread_stack';
+---------------+--------+
| Variable_name | Value  |
+---------------+--------+
| thread_stack  | 262144 |
+---------------+--------+
1 row in set (0.00 sec)

mysql> \s
--------------
mysql  Ver 14.14 Distrib 5.7.27, for Linux (x86_64) using  EditLine wrapper

Connection id:		18650
Current database:	tap
Current user:		paul@localhost
SSL:			Not in use
Current pager:		stdout
Using outfile:		''
Using delimiter:	;
Server version:		5.7.27-0ubuntu0.18.04.1-log (Ubuntu)
Protocol version:	10
```

I note that when it errored the stack setting was 196608 bytes, which would be the default for a 32 bit system https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_thread_stack](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_thread_stack). As far as I can remember, I haven't changed this from the default so I'm assuming you are running a 32 bit system.

What was the error once you restarted mysql with thread_stack = 512000?

**Comment by sq6jnx** [comment]
Thank you for response.

Interresting, after `$ sudo mysqld --thread_stack=512000` MySQL shows that thread_stack remained unchanged:

```
mysql> \s
--------------
mysql  Ver 14.14 Distrib 5.7.27, for Linux (x86_64) using  EditLine wrapper

Connection id:          1634
Current database:
Current user:           <user>@<hostname>
SSL:                    Not in use
Current pager:          stdout
Using outfile:          ''
Using delimiter:        ;
Server version:         5.7.27-0ubuntu0.18.04.1 (Ubuntu)
Protocol version:       10
Connection:             <hostname> via TCP/IP
Server characterset:    latin1
Db     characterset:    latin1
Client characterset:    utf8
Conn.  characterset:    utf8
TCP port:               3306
Uptime:                 8 days 17 hours 58 min 4 sec
```

Thank you, MySQL, for a definitive answer on how to increase thread_stack.

I'm going to poke with it in a moment, so please stay with me.

**Comment by animalcarpet** [comment]
The value in the mysql.cnf is probably wrong so try changing the line there
and see if it accepts the value after a restart.

**Comment by sq6jnx** [comment]
> The value in the mysql.cnf is probably wrong so try changing the line there

Gosh, you are faster than `sudo service mysql stop` :-)

In `mysqld.cnf ` I see `thread_stack            = 256K`, but I've followed instrunctions from https://askubuntu.com/a/821608, and now I see:

```
mysql> show variables like 'thread_stack';
+---------------+--------+
| Variable_name | Value  |
+---------------+--------+
| thread_stack  | 512000 |
+---------------+--------+
1 row in set (0.00 sec)
```

... aaand mytap was installed successfully. Thanks.

**Comment by sq6jnx** [comment]
I'd love to create merge request on this (too low thread_stack value), but where should I point it? On `./install` script, or maybe somwhere in test suite?

**Comment by animalcarpet** [comment]
Strange that it wasn't reading the value correctly. Do you have any old
versions of the cnf that it might be picking up?

Anyway, have fun with mytap. Suggest you try the autotap script if you want
to get started quickly with some tests.

**Comment by animalcarpet** [comment]
You'd need the package already installed to get mytap to do the test for
you. Could add a quick test in install.sh similar to existing version tests
but I think that might be overkill for an edge case. Should definitely go
in the README.md and the docs.
