### ISSUE TITLE
Typo in column name

### ISSUE THREAD

**Issue by quazgar** [hepabolu/mytap#52]
In [`mytap-column.sql`, line 395](../blob/0fbdab7ec4522be5dc179bc8946aebb30898dbe9/mytap-column.sql#L395), there's a typo `descriptio` which can be easily fixed.

It looks as if MR #51 already fixes this. Can that MR be merged and a new patch release be created?

**Comment by sq6jnx** [comment]
@animalcarpet If you want to just fix the typo we can just `cherry-pick` specific commit from #51 (3e8ff610394c584b0435133aa1efbbb509ff3994).

**Comment by hepabolu** [comment]
I merged the pull request. That should fix this issue.
